version: 3

services:
  prometheus:
    image: prom/prometheus
    expose:
      - 9090
    ports:
      - 9090:9090
  pushgateway:
    image: poom/pushgateway
    expose:
      - 9091
    ports:
      - 9091:9091